# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# The following environment variables must be set in the circleci project UI
#   - $IMAGE_NAME = anchore/engine-db-preload
#
# Define YAML anchors
.attach_workspace: &attach_workspace
  attach_workspace:
      at: /home/circleci/workspace

# Start circleci configuration
version: 2.1
jobs:
  build_dev_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh -s build dev
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images dev
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  run_dev_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Docker Compose & Run Tests
          command: scripts/build.sh -s test_built_images dev

  push_dev_dockerhub:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push to DockerHub
          command: scripts/build.sh -s push_all_versions dev

  build_v050_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.5.0
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.5.0
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  build_v051_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.5.1
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.5.1
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  build_v052_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.5.2
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.5.2
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  build_v060_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.6.0
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.6.0
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  build_test_push_v051_slim_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build, test and push slim image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s build_images v0.5.1
      - run:
          name: Save image to workspace
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s save_images v0.5.1
      - run:
          name: Test image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s test_built_images v0.5.1
      - run: 
          name: Push image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s push_all_versions v0.5.1

  build_test_push_v052_slim_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build, test and push slim image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s build_images v0.5.2
      - run:
          name: Save image to workspace
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s save_images v0.5.2
      - run:
          name: Test image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s test_built_images v0.5.2
      - run: 
          name: Push image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s push_all_versions v0.5.2

  build_test_push_v060_slim_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build, test and push slim image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s build_images v0.6.0
      - run:
          name: Save image to workspace
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s save_images v0.6.0
      - run:
          name: Test image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s test_built_images v0.6.0
      - run: 
          name: Push image
          command: IMAGE_REPO=docker.io/anchore/engine-db-preload-slim scripts/build.sh -s push_all_versions v0.6.0

  run_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Docker Compose & Run Tests
          command: scripts/build.sh test_built_images all

  push_dockerhub:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push to DockerHub
          command: scripts/build.sh push_all_versions all

workflows:
  default_workflow:
    jobs:
      - build_dev_image
      - run_dev_tests:
          requires:
            - build_dev_image
      - push_dev_dockerhub:
          context: dockerhub
          requires:
            - run_dev_tests
  
  nightly_build:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_test_push_v051_slim_image
      - build_test_push_v052_slim_image
      - build_test_push_v060_slim_image
      - build_v050_image
      - build_v051_image
      - build_v052_image
      - build_v060_image
      - run_tests:
          requires:
            - build_v050_image
            - build_v051_image
            - build_v052_image
            - build_v060_image
      - push_dockerhub:
          context: dockerhub
          requires:
            - run_tests
