# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# The following environment variables must be set in the circleci project UI
#   - $IMAGE_NAME = anchore/engine-db-preload
#
# Define YAML anchors
.attach_workspace: &attach_workspace
  attach_workspace:
      at: /home/circleci/workspace

# Start circleci configuration
version: 2.1
jobs:
  build_dev_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images dev
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images dev
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  run_dev_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Docker Compose & Run Tests
          command: scripts/build.sh test_built_images dev

  push_dev_dockerhub:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push to DockerHub
          command: scripts/build.sh push_all_versions dev

  build_v033_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.3.3
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.3.3
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*
  
  build_v034_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.3.4
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.3.4
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  build_v040_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.4.0
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.4.0
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*
  
  build_v041_image:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: scripts/build.sh build_images v0.4.1
      - run:
          name: Save image to workspace
          command: scripts/build.sh save_images v0.4.1
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  run_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Docker Compose & Run Tests
          command: scripts/build.sh test_built_images

  push_dockerhub:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push to DockerHub
          command: scripts/build.sh push_all_versions

workflows:
  default_workflow:
    jobs:
      - build_dev_image
      - run_dev_tests:
          requires:
            - build_dev_image
      - push_dev_dockerhub:
          context: dockerhub
          requires:
            - run_dev_tests
  
  nightly_build:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_v033_image
      - build_v034_image
      - build_v040_image
      - build_v041_image
      - run_tests:
          requires:
            - build_v033_image
            - build_v034_image
            - build_v040_image
            - build_v041_image
      - push_dockerhub:
          context: dockerhub
          requires:
            - run_tests
