# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# The following environment variables must be set in the circleci project UI
# - $IMAGE_NAME -> name of image to push to dockerhub
#
# Define YAML anchors
.attach_workspace: &attach_workspace
  attach_workspace:
      at: /home/circleci/workspace/

.install_dependencies: &install_dependencies
  run:
    name: install dependencies
    command: |
      pip install --upgrade pip
      pip install --upgrade docker-compose
      pip install --upgrade anchorecli

# Start circleci configuration
version: 2.1
jobs:
  build_images:
    machine: true
    steps:
      - checkout
      - <<: *install_dependencies
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: |
            set -x
            mkdir -p /home/circleci/workspace
            cp docker-compose.yaml /home/circleci/workspace/docker-compose.yaml
            source scripts/build.sh
            for version in $(cat .circleci/build_versions.txt); do
                cp -f /home/circleci/workspace/docker-compose.yaml docker-compose.yaml
                if docker pull ${IMAGE_NAME}:${version} &> /dev/null; then
                    sed -i "s|postgres:9|${IMAGE_NAME}:${version}|g" docker-compose.yaml
                fi
                setup_anchore_engine $version
                scripts/feed_sync_wait.py 240 30
                sudo rm -rf db
                docker tag ${IMAGE_NAME}:dev ${IMAGE_NAME}:dev-${version}
                save_image $version
            done
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*
            - docker-compose.yaml

  run_tests:
    machine: true
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *install_dependencies
      - run:
          name: Run built image with docker-compose & aetest.py
          command: |
            set -x
            source scripts/build.sh
            for version in $(cat .circleci/build_versions.txt); do
                cp -f /home/circleci/workspace/docker-compose.yaml docker-compose.yaml
                load_image $version
                sed -i "s|postgres:9|${IMAGE_NAME}:dev-${version}|g" docker-compose.yaml
                setup_anchore_engine $version
                run_tests $version
                sudo rm -rf db
            done

  push_dockerhub:
    machine: true
    steps:
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push dockerhub
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install -y git
            source scripts/build.sh
            for version in $(cat .circleci/build_versions.txt); do
                load_image $version
                push_dockerhub $version
            done

workflows:
  default_workflow:
    jobs:
      - build_images
      - run_tests:
          requires:
            - build_images
      - push_dockerhub:
          requires:
            - run_tests
  
  nightly_build:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_images
      - run_tests:
          requires:
            - build_images
      - push_dockerhub:
          requires:
            - run_tests
