# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# The following environment variables must be set in the circleci project UI
#   - $IMAGE_NAME = anchore/engine-db-preload
#
# Define YAML anchors
.attach_workspace: &attach_workspace
  attach_workspace:
      at: /home/circleci/workspace/

# Start circleci configuration
version: 2.1
jobs:
  build_images:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup Build Environment
          command: ./build.sh setup_build_environment
      - run:
          name: Setup Anchore Engine, Sync Feeds & Build Image
          command: ./build.sh build_and_save_image
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*
            - docker-compose.yaml

  run_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Install Dependencies
          command: ./build.sh install_dependencies
      - run:
          name: Docker Compose & Run Tests
          command: ./build.sh compose_up_and_test

  push_dockerhub:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - run:
          name: Push to DockerHub
          command: apk add bash && ./build.sh push_all_versions

workflows:
  default_workflow:
    jobs:
      - build_images
      - run_tests:
          requires:
            - build_images
      - push_dockerhub:
          context: dockerhub
          requires:
            - run_tests
  
  nightly_build:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_images
      - run_tests:
          requires:
            - build_images
      - push_dockerhub:
          context: dockerhub
          requires:
            - run_tests
